Documented Assignment Grading in Groups
CircuitVerse/CircuitVerseDocs pull request #192
Opened 2019-12-19 20:54 UTC by NumberC

Fixes #190 
To see changes, go to docs/groups.md

2019-12-20 16:05 UTC, PragatiVerma18 commented
Can you please fix the broken images as well before submitting for review again??

2019-12-20 16:44 UTC, NumberC commented
The images work now

2019-12-20 18:24 UTC, PragatiVerma18 approved these changes
Looks good to me! @satu0king, please review.

2020-01-19 14:24 UTC, JoshHeng requested changes
- Check capitalisation - there are some capitalised words which don't need to be capitalised
- Spaces are not needed between a word and a colon (`:`)
- There should be a slash before each image URL, as there was before
- Button names should have backticks instead of asterisks (`This` instead of **this**)

2020-01-19 14:24 UTC, JoshHeng commented on docs/groups.md
> +![student-stauts](images/student-status.png)
Check spelling of `[student-status]`

2020-01-19 14:24 UTC, JoshHeng commented on docs/groups.md
>  - Simply enter the list of emails separated by commas. (If students are already registered with CircuitVerse they will be added automatically. If they are not registered with CircuitVerse yet, an inv
A space is not needed between the full stop and end bracket. I'm not sure if brackets are needed at all.

2020-01-19 15:23 UTC, NumberC commented on docs/groups.md
>  - Simply enter the list of emails separated by commas. (If students are already registered with CircuitVerse they will be added automatically. If they are not registered with CircuitVerse yet, an inv
Should I though? I just noticed another PR for this issue was merged, and now, the issue is closed.

2026-03-13 01:25 UTC, closed without merging