Added information for Groups Page
CircuitVerse/CircuitVerseDocs pull request #197
Opened 2019-12-26 19:45 UTC by JyothsnaAshok

Fixes [#144](https://github.com/CircuitVerse/CircuitVerse/issues/114)

#### Describe the changes you have made -
I've added more information about collaborations, how to submit assignments and fixed some typos as well.

[GCI Task](https://codein.withgoogle.com/dashboard/task-instances/6269829040832512/)

2019-12-27 04:04 UTC, sakshi1499 commented
The changes look good. Can you add a screenshot of the same here also? @JyothsnaAshok

2019-12-27 19:32 UTC, JyothsnaAshok commented
@sakshi1499 I've added the Screenshots of the changes.

2019-12-28 05:11 UTC, sakshi1499 commented
Good work! 💯

2019-12-28 11:01 UTC, JyothsnaAshok commented
@sakshi1499 Thanks!

2020-01-19 14:17 UTC, JoshHeng requested changes
Good work but check the use of punctuation:
- There are too many capital letters used when they are not needed
- Names of buttons should be used with backticks instead of asterisks (`This` instead of **this**)
- No space is needed between a word and a colon (`This:` instead of `This :`)

I have flagged the majority of these.

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
> +> One of the Versatile Feature of CircuitVerse assists Teachers in Managing Class Assignments. Teachers can add students to groups, post assignments with deadlines and also grade the assignments usin
`One of the features of CircuitVerse allows teachers to manage class assignments`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
> +**Teachers can :**
`**Teachers can:**`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
>  - Add Students
`Add students`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
>  - Post Assignments
`Post assignments`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
> +- View Assignment Work of each Student/Member.
`View the assignment responses of each student/member`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
> +**Students can :**
`**Students can:**`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
>  - View the Given Assignment with live deadline counter.
`View their assignments with a live deadline timer`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
>  - Create them easily with the help of CircuitVerse Simulator.
`Create circuits easily with the CircuitVerse simulator`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
>  - Submit them remotely.
`Submit responses remotely`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
>   After adding members, Click on the **ADD new assignment** Button.
Should be use backticks instead of `**` for semantics.
`Click` and `Button` do not need to be capitalised

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
> + Fill Up all the necessary Details like :
`Fill up all the necessary details such as:`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
> + - Set the Deadline (both Date and Time)
`Date` and `Time` do not need to be capitalised

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
> + - Assignment description : Detailed Description of what the assignment is all about, tools and circuits to be used etc.
`Assignment description: detailed description of what the assignment is all about, tools and circuits to be used, etc.`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
> +> **NOTE :** Word Processing tools are available for Description as well as an option to embed any file for Assignment Description.
`**Note:** Word processing tools and the ability to embed files are available for the description`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
> +> After Posting, to see the status of different assignments, Click on the **Show** button corresponding to a group.
`Posting` and `Click` do not need to be capitalised

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
> +- Different groups must be visible which are created by their Teachers in **Groups You belong to** Window.
`Teachers`  and `Window` do not need to be capitalised. Backticks should be used instead of `**`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
> +**Show** Button : Displays the details and Description of the Assignment.
`**Show** Button: Displays the details and the description of the assignment.`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
> +**Start Working** Button : It Would Open a New Window.
`**Start Working** button: Opens a new window.`

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
> + - To start working on your assignment, click on the **Launch Simulator** Button.
`Button` does not need to be capitalised

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
>   - To preview, Click on **Preview** Button.
`Click` and `Button` do not need to be capitalised

2020-01-19 14:17 UTC, JoshHeng commented on docs/groups.md
>   - To work in Group (for group assignment), Click on **Add Collaborator** Button.
`Group`, `Click` and `Button` do not need to be capitalised

2026-05-25 14:34 UTC, closed without merging