LMS Integration Project Documentation | GSoC'21 Ayan Biswas
CircuitVerse/CircuitVerseDocs pull request #304
Opened 2021-07-27 12:17 UTC by ayan-biswas0412

Fixes #303 

#### Changes done:
- [x] Added ```docs/chapter2/lmsintegration.md```.
- [x] Written documentation about how to use CircuitVerse as an LTI External Tool with different LMS
- [x] Written documentation about how to add CircuitVerse with LMSs
   - [x] Written instructions for Moodle
   - [x] Written instructions for Canvas
   - [x] Written instructions for Sakai
   - [x] Any other generic LTI Supported LMS

#### Screenshots:

#### Preview Link(s):

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add a link from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

2021-07-27 12:45 UTC, Shivansh2407 requested changes
Nice Work @ayan-biswas0412 :+1: I have suggested a few changes here. Please updated them and we'll be good to go :tada: 
Also please add the screenshots for the changes you've made. 
Thanks & Happy Coding !

2021-07-27 12:45 UTC, Shivansh2407 commented on docs/chapter2/lmsintegration.md
> +Contributing Authors: [@ayan-biswas0412](https:github.com/ayan-biswas0412)
Please remove this contributing author tag.

2021-07-27 12:45 UTC, Shivansh2407 commented on docs/_sidebar.md
> +    * [Integrate CircuitVerse with LMS](/chapter2/lmsintegration.md)
Make sure you follow the file naming convention here to avoid issues in future. Rename the file to something like 4lmsintegration or if you want it to be here at 3, then you will have to change the other filename as well.

2021-07-27 12:45 UTC, Shivansh2407 commented on docs/chapter2/lmsintegration.md
> +# Integrate with Learning Management Systems
Keep the heading here, similar to the one mentioned in the sidebar. "Integrate CircuitVerse with LMS"

2021-07-27 15:57 UTC, ayan-biswas0412 commented on docs/chapter2/lmsintegration.md
> +# Integrate with Learning Management Systems
Done

2021-07-27 15:59 UTC, ayan-biswas0412 commented on docs/_sidebar.md
> +    * [Integrate CircuitVerse with LMS](/chapter2/lmsintegration.md)
I think the numbering convention will make error in future because as per the topic my topic is appropriate for position 3 but I am afraid to make the filename prefixed with 3 because there may be a lot of files be inserted in this folder and later point we have to again rename those files one by one.
Please give your suggestions also. @tachyons

2021-07-27 16:04 UTC, ayan-biswas0412 commented on docs/_sidebar.md
> +    * [Integrate CircuitVerse with LMS](/chapter2/lmsintegration.md)
For now I have modified the filename and kept mine in number 3 and changed the previous 3 to 4
cc @Shivansh2407

2021-07-27 16:05 UTC, ayan-biswas0412 commented on docs/chapter2/lmsintegration.md
> +Contributing Authors: [@ayan-biswas0412](https:github.com/ayan-biswas0412)
yah done

2021-07-29 14:11 UTC, Shivansh2407 approved these changes
Looks good to me @ayan-biswas0412 :+1: Great work :tada:

2021-07-29 14:12 UTC, merged