fix(ui): searchbar & navbar overlapping fix
CircuitVerse/CircuitVerseDocs pull request #341
Opened 2023-02-23 15:30 UTC by Arnabdaz

Fixes #339

Ref #339 

#### Changes done:
- [x] fix overlapping of search results 
- [x] fix search bar spacing 

#### Screenshots:

![image](https://user-images.githubusercontent.com/96580571/219972312-ab498aaf-bb54-4de7-ad74-f48aaa9fa0f6.png)

#### Preview Link(s):

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2023-02-23 16:12 UTC, vedant-jain03 requested changes

2023-02-23 16:12 UTC, vedant-jain03 commented on docs/styles/theme.css
> +  border-bottom: 4px dashed var(--accent);
```suggestion
border-bottom: 1px solid var(--accent);
```

This looks more decent, WDYT?
We can add bottom `box-shadow` as well!

2023-02-23 16:32 UTC, Arnabdaz commented on docs/styles/theme.css
> +  border-bottom: 4px dashed var(--accent);
sure let me do the changes

2023-02-23 16:45 UTC, Arnabdaz commented on docs/styles/theme.css
> +  border-bottom: 4px dashed var(--accent);
![image](https://user-images.githubusercontent.com/96580571/220973456-caa4f483-3215-46e2-b039-a1f7bba94ff4.png)
@vedant-jain03 is this enough?

2023-02-24 03:01 UTC, vedant-jain03 commented on docs/styles/theme.css
> +  border-bottom: 4px dashed var(--accent);
LGTM!

2023-02-24 08:02 UTC, Arnabdaz commented
@vedant-jain03 pushed with requested changes please take a look

2023-03-01 03:24 UTC, vedant-jain03 approved these changes
Good work @Arnabdaz 💯

2025-05-27 09:18 UTC, closed without merging