feat(docs): added documentation for force gate
CircuitVerse/CircuitVerseDocs pull request #354
Opened 2023-10-14 16:45 UTC by niladrix719

Fixes #343

#### Changes done:
- [x] Added Documentation for Force Gate

#### Screenshots:

![Screenshot 2023-10-14 at 10 05 28 PM](https://github.com/CircuitVerse/CircuitVerseDocs/assets/91966855/c60bbabb-c645-429f-be6f-cd60dc30ec50)
![Screenshot 2023-10-14 at 10 05 52 PM](https://github.com/CircuitVerse/CircuitVerseDocs/assets/91966855/7a767127-a771-4248-b693-1323b071120c)

#### Preview Link(s):

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2023-10-14 16:49 UTC, niladrix719 commented
cc @Prerna-0202

2023-12-10 16:29 UTC, ayanbiswas-ixana requested changes
.

2023-12-10 16:34 UTC, ayan-biswas0412 requested changes
What is a force gate? I got your idea but still wondering if this terminology even make sense ? Like I have never encountered this term "force gate" in VLSI design.

Can you please cite any source any paper or book where "force gate" term has been used ?

and I believe it is more of a tri-state buffer logic.

2023-12-10 16:36 UTC, niladrix719 commented
@ayanbiswas-ixana When writing documentation, I couldn't find information outside of CircuitVerse. Based on what I learned using this element i wrote that. like its properties and all

2023-12-10 16:38 UTC, ayanbiswas-ixana commented
> @ayan-biswas0412 When writing documentation, I couldn't find information outside of CircuitVerse. Based on what I learned using this element i wrote that. like its properties and all

yeah got your point, @Prerna-0202 looking forward to your comments. Do we really need to add this as a "force gate" because it is simple a latch or a tri-state buffer which sense enable signal and sends input to output.

2023-12-10 16:38 UTC, ayan-biswas0412 commented
> @ayan-biswas0412 When writing documentation, I couldn't find information outside of CircuitVerse. Based on what I learned using this element i wrote that. like its properties and all

yeah got your point, @Prerna-0202 looking forward to your comments. Do we really need to add this as a "force gate" because it is simple a latch or a tri-state buffer which sense enable signal and sends input to output.

2025-03-13 16:40 UTC, closed without merging