migrated the website to Docusaurus
CircuitVerse/CircuitVerseDocs pull request #386
Opened 2024-11-19 17:44 UTC by salmoneatenbybear

Fixes #383

#### Changes done:
- [x] Migrated documentation from **Docsify** to **Docusaurus**.
- [x] Updated the entire structure of the documentation to align with Docusaurus' default structure for better maintainability and SEO.
- [x] Included the new Docusaurus configuration and removed existing Docsify-specific files.
- [x] Implemented the new search feature using `@easyops-cn/docusaurus-search-local`.

#### Screenshots:
Since this is a major structural and styling migration, please refer to the **video demonstration** showcasing the updated website here:  

https://github.com/user-attachments/assets/6776180f-bdc1-4daa-91bf-c9c559a0bb61

#### Preview Link(s):
- [Updated Docusaurus documentation website](https://circuitverse-docs.netlify.app/)

PLEASE NOTE THAT THE PREVIEW LINK IS PUBLISHING FROM A REPO I MADE FOR TESTING THIS SITE ONCE EVERYTHING IS APPROVED THIS NEEDS TO BE CHANGED TO BE PUBLISHING FROM THIS REPO.

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried squashing the commits into one

2024-11-19 17:48 UTC, salmoneatenbybear commented
@tachyons please review once you are free :)

2025-01-21 17:06 UTC, ThatDeparted2061 reviewed
I am guessing since the data is directly from the current docs, reviewing the configs should be enough to get this running.

2025-01-21 18:35 UTC, SharonIV0x86 commented
@ThatDeparted2061 can you add me as a reviewer it seems like i dont have the permission.

2025-01-21 18:38 UTC, SharonIV0x86 commented on CircuitVerse-Documentation/docs/chapter4/6sequentialelements.mdx
> +As the name suggests, the **ROM **( read-only memory) circuit element stores read only data for computers and other electronic devices. ROM is mostly used for firmware updates. A simple example of RO
```suggestion
As the name suggests, the **ROM** ( read-only memory) circuit element stores read only data for computers and other electronic devices. ROM is mostly used for firmware updates. A simple example of ROM is the cartridge used with video game consoles, which allows one system to run multiple games. Another example of ROM is EEPROM, which is a programmable ROM used for the computer BIOS.
```

2025-01-21 18:38 UTC, SharonIV0x86 commented on CircuitVerse-Documentation/docs/chapter4/6sequentialelements.mdx
> +You can verify the behavior of the **RAM **circuit element in the live circuit embedded below:
```suggestion
You can verify the behavior of the **RAM** circuit element in the live circuit embedded below:
```

2025-01-21 18:40 UTC, SharonIV0x86 requested changes
These sections:
- RAM
- ROM
- Clock
Have incorrectly placed * for bold formatting which needs to be fixed.

2025-01-21 18:44 UTC, SharonIV0x86 commented
@salmoneatenbybear A few diagrams in Chapter 4 have black text on them, when switched to dark mode these images are barely visible [here](https://circuitverse-docs.netlify.app/chapter4/chapter4-sequentialelements#jk-flip-flop)

2025-01-21 18:49 UTC, ManishG04 commented on CircuitVerse-Documentation/docs/chapter5/usingeditlayout.mdx
> +title: "Usingeditlayout"
```suggestion
title: "Using Edit Layout"
```

2025-01-21 18:50 UTC, ManishG04 commented on CircuitVerse-Documentation/docs/chapter5/usingsubcircuits.mdx
> +title: "Usingsubcircuits"
```suggestion
title: "Using Sub-Circuits"
```

2025-01-21 18:56 UTC, ManishG04 reviewed
@salmoneatenbybear Almost all chapter titles have spacing issues in frontmatter

2025-01-21 19:03 UTC, ManishG04 commented on CircuitVerse-Documentation/docs/chapter2/2cvforeducators.mdx
> +[insert embed video]
Video needs to be inserted here

2025-01-21 19:04 UTC, SharonIV0x86 commented on CircuitVerse-Documentation/docs/chapter7/2buildwithcv.mdx
> +   Watch this video for more information on the different fields that can be used for sharing more information about the project.
Video is not listed.

2025-01-21 19:08 UTC, SharonIV0x86 commented on CircuitVerse-Documentation/docs/chapter4/3output.mdx
> +The **HexDisplay** is more simple to use than the** SevenSegDisplay** and **SixteenSegDisplay **circuit elements. Since it takes a 4-bit input and can display integers 1 through 9 and the letters A t
```suggestion
The **HexDisplay** is more simple to use than the **SevenSegDisplay** and **SixteenSegDisplay** circuit elements. Since it takes a 4-bit input and can display integers 1 through 9 and the letters A through F, there is less room for customization.
```

2025-01-21 19:12 UTC, SharonIV0x86 commented on CircuitVerse-Documentation/docs/chapter4/6sequentialelements.mdx
> +> Properties that can be customized in the **PROPERTIES** panel include:\*\* **BitWidth**
This is not rendering properly additional ** are visible.

2025-01-21 19:13 UTC, ManishG04 commented on CircuitVerse-Documentation/docs/chapter4/8misc.mdx
> +The **Adder** circuit element is a logical circuit of a full adder that performs an addition operation on binary numbers and produces a sum of the three inputs and a carry value (Cout). Figure 4.18 d
```suggestion
The **Adder** circuit element is a logical circuit of a full adder that performs an addition operation on binary numbers and produces a sum of the three inputs and a carry value (Cout). Figure 4.18 displays the different pins available for the **Adder** circuit element within CircuitVerse and Table 4.21 shares a brief description of the same.
```

2025-01-21 19:13 UTC, ManishG04 commented on CircuitVerse-Documentation/docs/chapter4/7annotation.mdx
> +> Properties that can be customized in the **PROPERTIES** panel include:\*\* **Font size**
```suggestion
> Properties that can be customized in the **PROPERTIES** panel include: **Font size**
```

2025-01-21 19:14 UTC, ManishG04 commented on CircuitVerse-Documentation/docs/chapter2/3lmsintegration.mdx
> +2. Click on the **+Add Assignment** button.
```suggestion
2. Click on the **+ Add Assignment** button.
```

2025-01-21 19:14 UTC, ManishG04 commented on CircuitVerse-Documentation/docs/chapter2/3lmsintegration.mdx
> +6. Click **+App**.
```suggestion
6. Click **+ App**.
```

2025-01-21 19:16 UTC, ManishG04 commented on CircuitVerse-Documentation/docs/chapter4/8misc.mdx
> +> Properties that can be customized in the **PROPERTIES** panel include**: **BitWidth, Orientation, Debug Flag identifier\*\*
```suggestion
> Properties that can be customized in the **PROPERTIES** panel include: **BitWidth, Orientation, Debug Flag identifier**
```

2025-01-21 19:20 UTC, ManishG04 requested changes
@salmoneatenbybear These are some problems I found

2025-01-22 01:07 UTC, salmoneatenbybear commented
@SharonIV0x86 @ManishG04 @ThatDeparted2061 

Thanks for taking the time to find these issues 

Please check out the repo for this site 

https://github.com/salmoneatenbybear/circuitverse-docs

Please could you guys create issues for this there and then we can take it from there...

2025-01-22 02:41 UTC, ThatDeparted2061 commented
> @salmoneatenbybear A few diagrams in Chapter 4 have black text on them, when switched to dark mode these images are barely visible [here](https://circuitverse-docs.netlify.app/chapter4/chapter4-sequentialelements#jk-flip-flop)

Great find we shud have dynamic colouring for the digram labeling for light and dark mode

2025-01-22 02:55 UTC, SharonIV0x86 commented
> @SharonIV0x86 @ManishG04 @ThatDeparted2061 
> 
> Thanks for taking the time to find these issues 
> 
> Please check out the repo for this site 
> 
> https://github.com/salmoneatenbybear/circuitverse-docs
> 
> Please could you guys create issues for this there and then we can take it from there...

Alright, I'll open an issue for each of the changes.

2025-01-22 08:14 UTC, ManishG04 commented
> @SharonIV0x86 @ManishG04 @ThatDeparted2061
> 
> Thanks for taking the time to find these issues
> 
> Please check out the repo for this site
> 
> https://github.com/salmoneatenbybear/circuitverse-docs
> 
> Please could you guys create issues for this there and then we can take it from there...

Alright, I will be opening the issues, I accidentaly opened one issue in this repo only I closed it sorry for that I have just started Open Source

2025-01-22 10:22 UTC, ThatDeparted2061 commented
> > @SharonIV0x86 @ManishG04 @ThatDeparted2061
> > 
> > Thanks for taking the time to find these issues
> > 
> > Please check out the repo for this site
> > 
> > https://github.com/salmoneatenbybear/circuitverse-docs
> > 
> > Please could you guys create issues for this there and then we can take it from there...
> 
> Alright, I will be opening the issues, I accidentaly opened one issue in this repo only I closed it sorry for that I have just started Open Source 

It's not a problem, you re just learning. You can always close the PR.
REGARDS

2025-04-17 05:30 UTC, closed without merging