Added a file on Minimization Techniques
CircuitVerse/CircuitVerseDocs pull request #45
Opened 2019-03-23 07:13 UTC by Reetoo

Fixes #9 

#### I have added a file on minimization techniques containing K-map (I'm further working on it for improving it) which is according to the Project 5 of Google Summer of Code since I want to work for CircuitVerse projects. I have also corrected some spelling errors.

#### Screenshots of the changes -
![a](https://user-images.githubusercontent.com/34961676/54863002-d8c16000-4d68-11e9-838a-25dd9fedb778.png)

2019-03-23 09:55 UTC, satu0king commented
Please understand that the purpose of the documentation is on how to use CircuitVerse, not digital logic design. The GSoC'19 project for interactive book will be on digital logic design. 

If you add documentation on how to use the combinational analysis module of CircuitVerse along with the current documentation, we can merge.

2019-03-23 10:36 UTC, Reetoo commented
So what exactly should I be working on so as to get selected for GSoC?

On Sat, Mar 23, 2019, 3:25 PM Satvik Ramaprasad <notifications@github.com>
wrote:

> Please understand that the purpose of the documentation is on how to use
> CircuitVerse, not digital logic design. The GSoC'19 project for interactive
> book will be on digital logic design.
>
> If you add documentation on how to use the combinational analysis module
> of CircuitVerse along with the current documentation, we can merge.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CircuitVerse/CircuitVerseDocs/pull/45#issuecomment-475856325>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AhV5DD87F7AkxBRiDYorfaR4y4jqIJpzks5vZfn1gaJpZM4cEwza>
> .
>

2019-03-23 10:38 UTC, satu0king commented
We will review PRs in this repository for the 5th project, however the 5th project will not be in this project. Nevertheless, it will be similar kinds of work.

2019-03-23 13:20 UTC, Reetoo commented
I have added a documentation on using the Combinational Analysis. Please look into it.

2019-03-25 04:01 UTC, Reetoo commented
Have a look at this

2019-03-26 15:38 UTC, Reetoo commented
Added a document on flipflop. Please have a look.

2019-03-31 16:51 UTC, satu0king requested changes

2019-03-31 16:51 UTC, satu0king commented on docs/minimization.md
> +![Alt text](https://cdn1.imggmi.com/uploads/2019/3/23/5c64d0c7ed0655f7e7ecd468da833398-full.png)
Please add images to the repository. It is not a good idea to serve content from a third party website.

2019-03-31 16:51 UTC, satu0king commented on docs/flipflop.md
> +<iframe width="600px" height="400px" src="https://circuitverse.org/simulator/edit/12500" id="projectPreview" scrolling="no" webkitAllowFullScreen mozAllowFullScreen allowFullScreen> </iframe>
Separate changes have to be in different PRs.

2019-03-31 16:51 UTC, satu0king commented on docs/combination.md
> +<iframe width="600px" height="400px" src="https://circuitverse.org/simulator/edit/12119" id="projectPreview" scrolling="no" webkitAllowFullScreen mozAllowFullScreen allowFullScreen> </iframe>
As previously mentioned, this not a repository for digital logic design. It is on the usage of CircuitVerse.

2026-05-25 14:08 UTC, Yana-do-code commented
From the previous comments , it is invalid .

2026-05-25 14:08 UTC, closed without merging