creates flip-flop-uses.md
CircuitVerse/CircuitVerseDocs pull request #61
Opened 2019-03-24 19:41 UTC by MonilBhavsar

Fixes #1 

#### Describe the changes you have made - I have created flip flop applications / uses Markdown file.

#### Screenshots of the changes (If any) -

2020-06-27 18:43 UTC, gaurivn requested changes

2020-06-27 18:43 UTC, gaurivn commented on docs/flip-flop-uses.md
> +Flip-Flops have a wide range of application where the exisiting state has to execute or process depending on the previous state.
```suggestion
Flip-Flops have a wide range of applications where the existing state has to execute or process depending on the previous state.
```

2020-06-27 18:43 UTC, gaurivn commented on docs/flip-flop-uses.md
> +store multiple bit data. This is where Registers comes into action. Register is used to store 'n' bit data. Register is made by combibing flip flops.
```suggestion
store multiple bit data. This is where Registers come into action. A register is used to store 'n' bit data. A register is made by combining flip flops.
```

2020-06-27 18:43 UTC, gaurivn commented on docs/flip-flop-uses.md
> +As flip-flops can only store 1 bit , 'n' flip-flops combine together to store 'n' bit data.For example:- If a register stores 8 bit data, then it is a collection of
```suggestion
As a flip-flop can only store 1 bit , 'n' flip-flops combine together to store 'n' bit data.For example:- If a register stores 8 bit data, then it is a collection of
```

2020-06-27 18:43 UTC, gaurivn commented on docs/flip-flop-uses.md
> +When a number of flip flops are connected in series, this arrangement is called a Register.Register can be further classified into two types:-
```suggestion
When a number of flip flops are connected in series, this arrangement is called a Register. Register can be further classified into two types:-
```

2020-06-27 18:43 UTC, gaurivn commented on docs/flip-flop-uses.md
> +The registers which function upon asynchronous trigers are known as “Asynchronous shift registers”.
```suggestion
The registers which function upon asynchronous triggers are known as “Asynchronous shift registers”.
```

2020-06-27 18:43 UTC, gaurivn commented on docs/flip-flop-uses.md
> +This registers either work for positive clock pulse or negative clock pulse depending upon their triggering.
```suggestion
These registers either work for positive clock pulse or negative clock pulse depending on their triggering.
```

2020-06-27 18:43 UTC, gaurivn commented on docs/flip-flop-uses.md
> +Counters are a specific type of sequential circuit which stores how much time a process has occured during a given clock pulse.
```suggestion
Counter is a specific type of sequential circuit which stores how much time a process has occurred during a given clock pulse.
```

2020-07-01 11:59 UTC, YashKumarVerma commented
@gaurivn  Can you send a fresh PR for this? I think the original author is inactive.

2020-07-01 13:17 UTC, gaurivn commented
Sure, will send

2026-05-25 14:12 UTC, Yana-do-code commented
No longer needed.

2026-05-25 14:12 UTC, closed without merging